'use strict';

// data/countries.json is generated by scripts/build.js from the per-country
// files under countries/.  It arrives pre-joined and in canonical order, so
// there is one parse and no assembly work at require time.

var records = require('./data/countries.json');
var provincesByCode = require('./data/provinces.json');

var self = module.exports = {
    all: {},
    cache: {},

    findByIso2: code => transform(self.all[code]),
    findByIso3: code => find('iso3', code),
    findByName: name => find('name', name),
    findByCapital: name => find('capital', name),
    findByCurrency: code => find('currency', code),

    findByProvince(name) {
        if (!self.cache.province) self.cache.province = {};
        if (!(name in self.cache.province))
            self.cache.province[name] = pack(provinceIndex().get(name));
        return copy(self.cache.province[name]);
    },

    findByPhoneNbr(nbr) {
        // a lookup has no business throwing on bad input: 3.1.8 raised a
        // TypeError for anything that was not a string, where every other
        // finder simply returned undefined
        if (typeof nbr != 'string') return;

        nbr = nbr.replace(/\D/g, '');
        if (!nbr) return;

        // probe one hash per distinct prefix length, longest first, rather
        // than testing the number against all 250 prefixes
        var hits = [];
        for (var i = 0; i < prefixLengths.length; i++) {
            var found = byPrefix[nbr.slice(0, prefixLengths[i])];
            if (found) hits = hits.concat(found);
        }
        return pack(hits);
    },

    // these close over `self` rather than using `this` so that they survive
    // being destructured off the module: `const {names} = require(...)`
    ls(field) {
        return records.map(r => r[field]);
    },
    continents() {
        return self.ls('continent').unique();
    },
    names() {
        return self.ls('name');
    },
    capitals() {
        return self.ls('capital');
    }
};

// -- the public country shape ------------------------------------------------

// callers see currency and the ISO codes grouped; the stored record keeps them
// flat because that is what the data files hold

function transform(r) {
    if (!r) return;
    return {
        name: r.name,
        continent: r.continent,
        region: r.region,
        capital: r.capital,
        currency: {
            code: r.currency,
            symbol: r.currency_symbol,
            decimal: r.currency_decimal,
        },
        dialing_code: r.dialing_code,
        provinces: r.provinces,
        code: {iso2: r.iso2, iso3: r.iso3},
    };
}

// no match is undefined, one match is the country itself, several are an
// array -- the shape callers have always seen

function pack(list) {
    if (!list || !list.length) return;
    return list.length == 1 ? transform(list[0]) : list.map(transform);
}

// cached results are rebuilt on the way out.  3.1.8 handed back the very
// object it had cached, so a caller who wrote to a result poisoned the cache
// for the whole process: after `findByName('Denmark').name = 'x'`, every
// later lookup of Denmark answered 'x'.

function copy(packed) {
    if (!packed) return;
    return Array.isArray(packed) ? packed.map(clone) : clone(packed);
}

function clone(c) {
    return {
        name: c.name,
        continent: c.continent,
        region: c.region,
        capital: c.capital,
        currency: {
            code: c.currency.code,
            symbol: c.currency.symbol,
            decimal: c.currency.decimal,
        },
        dialing_code: c.dialing_code,
        provinces: c.provinces,
        code: {iso2: c.code.iso2, iso3: c.code.iso3},
    };
}

function find(field, value) {
    if (!(field in self.cache)) self.cache[field] = {};
    if (!(value in self.cache[field]))
        self.cache[field][value] = pack(index[field][value]);
    return copy(self.cache[field][value]);
}

// -- indexes -----------------------------------------------------------------

var index = {iso3: {}, name: {}, capital: {}, currency: {}};
var byPrefix = {};
var prefixLengths = [];

(function build() {
    var lengths = {};

    for (var i = 0; i < records.length; i++) {
        var r = records[i];

        // the key has to exist and be undefined rather than be absent:
        // `'provinces' in country` is true for all 250, and reads as
        // undefined for the 219 that have none
        r.provinces = provincesByCode[r.iso2];

        self.all[r.iso2] = r;

        for (var f in index) {
            var v = r[f];
            (index[f][v] || (index[f][v] = [])).push(r);
        }

        var prefix = r.dialing_code.replace(/\D/g, '');
        if (!prefix) continue;

        // unshift, not push.  3.1.8 ordered its prefix table with
        // `(a, b) => a.nbr.length < b.nbr.length ? 1 : -1`, which answers -1
        // for equal lengths -- an inconsistent comparator whose observable
        // effect is to reverse each group of same-length prefixes.  That is
        // why +1 answers [UM, US, Canada] and not [Canada, US, UM].  Encoded
        // here rather than left to depend on the engine's sort.
        (byPrefix[prefix] || (byPrefix[prefix] = [])).unshift(r);
        lengths[prefix.length] = true;
    }

    // longest prefix first, so +1-246 leads Barbados ahead of the +1 block
    prefixLengths = Object.keys(lengths).map(Number).sort((a, b) => b - a);
})();

// province lookup is built on the first call rather than at load: it walks
// 1432 subdivisions and their aliases, and most callers never ask

var provinces = null;

function provinceIndex() {
    if (provinces) return provinces;
    provinces = new Map();

    var add = (key, r) => {
        var list = provinces.get(key);
        if (!list) provinces.set(key, [r]);
        else if (list[list.length - 1] !== r) list.push(r);
    };

    for (var i = 0; i < records.length; i++) {
        var r = records[i];
        for (var j = 0; j < (r.provinces || []).length; j++) {
            var p = r.provinces[j];
            add(p.name, r);

            // an alias is an array or null.  Three entries used to carry a
            // bare string, and String.indexOf is a substring search, so
            // findByProvince('B') answered Vietnam by way of 'Binh Phuoc'.
            var alias = p.alias;
            if (!alias) continue;
            if (!Array.isArray(alias)) alias = [alias];
            for (var k = 0; k < alias.length; k++) add(alias[k], r);
        }
    }
    return provinces;
}

// -- Array.prototype ---------------------------------------------------------

// installed for the convenience of callers, but they must not be enumerable:
// an enumerable prototype property shows up in every for..in loop over an
// array in the host application

Object.defineProperty(Array.prototype, 'unpack', {
    configurable: true,
    writable: true,
    enumerable: false,
    value: function () {
        var l = this.length;
        return l == 1 ? this[0]
            : l == 0 && arguments.length > 0
            ? undefined
            : this;
    }
});

Object.defineProperty(Array.prototype, 'unique', {
    configurable: true,
    writable: true,
    enumerable: false,
    value: function () {
        return this.filter((e, pos) => this.indexOf(e) == pos);
    }
});
