export const all: {};
export const cache: {};
export function findByIso2(code: any): any;
export function findByIso3(code: any): any;
export function findByName(name: any): any;
export function findByCapital(name: any): any;
export function findByCurrency(code: any): any;
export function findByProvince(name: any): any;
export function findByPhoneNbr(nbr: any): any;
export function ls(field: any): any[];
export function continents(): any;
export function names(): any[];
export function capitals(): any[];
